export default {
  key: '1L2Y',
  name: 'TRP-Cage',
  chains: [{
    name: 'A',
    residues: [{
      symbol: 'N',
      label: '1'
    }, {
      symbol: 'L',
      label: '2'
    }, {
      symbol: 'Y',
      label: '3'
    }, {
      symbol: 'I',
      label: '4'
    }, {
      symbol: 'Q',
      label: '5'
    }, {
      symbol: 'W',
      label: '6'
    }, {
      symbol: 'L',
      label: '7'
    }, {
      symbol: 'K',
      label: '8'
    }, {
      symbol: 'D',
      label: '9'
    }, {
      symbol: 'G',
      label: '10'
    }, {
      symbol: 'G',
      label: '11'
    }, {
      symbol: 'P',
      label: '12'
    }, {
      symbol: 'S',
      label: '13'
    }, {
      symbol: 'S',
      label: '14'
    }, {
      symbol: 'G',
      label: '15'
    }, {
      symbol: 'R',
      label: '16'
    }, {
      symbol: 'P',
      label: '17'
    }, {
      symbol: 'P',
      label: '18'
    }, {
      symbol: 'P',
      label: '19'
    }, {
      symbol: 'S',
      label: '20'
    }]
  }]
};
