export default {
  key: '4INS',
  name: 'insulin',
  chains: [{
    name: 'A',
    residues: [{
      symbol: 'G',
      label: '1'
    }, {
      symbol: 'I',
      label: '2'
    }, {
      symbol: 'V',
      label: '3'
    }, {
      symbol: 'E',
      label: '4'
    }, {
      symbol: 'Q',
      label: '5'
    }, {
      symbol: 'C',
      label: '6'
    }, {
      symbol: 'C',
      label: '7'
    }, {
      symbol: 'T',
      label: '8'
    }, {
      symbol: 'S',
      label: '9'
    }, {
      symbol: 'I',
      label: '10'
    }, {
      symbol: 'C',
      label: '11'
    }, {
      symbol: 'S',
      label: '12'
    }, {
      symbol: 'L',
      label: '13'
    }, {
      symbol: 'Y',
      label: '14'
    }, {
      symbol: 'Q',
      label: '15'
    }, {
      symbol: 'L',
      label: '16'
    }, {
      symbol: 'E',
      label: '17'
    }, {
      symbol: 'N',
      label: '18'
    }, {
      symbol: 'Y',
      label: '19'
    }, {
      symbol: 'C',
      label: '20'
    }, {
      symbol: 'N',
      label: '21'
    }]
  }, {
    name: 'B',
    residues: [{
      symbol: 'F',
      label: '1'
    }, {
      symbol: 'V',
      label: '2'
    }, {
      symbol: 'N',
      label: '3'
    }, {
      symbol: 'Q',
      label: '4'
    }, {
      symbol: 'H',
      label: '5'
    }, {
      symbol: 'L',
      label: '6'
    }, {
      symbol: 'C',
      label: '7'
    }, {
      symbol: 'G',
      label: '8'
    }, {
      symbol: 'S',
      label: '9'
    }, {
      symbol: 'H',
      label: '10'
    }, {
      symbol: 'L',
      label: '11'
    }, {
      symbol: 'V',
      label: '12'
    }, {
      symbol: 'E',
      label: '13'
    }, {
      symbol: 'A',
      label: '14'
    }, {
      symbol: 'L',
      label: '15'
    }, {
      symbol: 'Y',
      label: '16'
    }, {
      symbol: 'L',
      label: '17'
    }, {
      symbol: 'V',
      label: '18'
    }, {
      symbol: 'C',
      label: '19'
    }, {
      symbol: 'G',
      label: '20'
    }, {
      symbol: 'E',
      label: '21'
    }, {
      symbol: 'R',
      label: '22'
    }, {
      symbol: 'G',
      label: '23'
    }, {
      symbol: 'F',
      label: '24'
    }, {
      symbol: 'F',
      label: '25'
    }, {
      symbol: 'Y',
      label: '26'
    }, {
      symbol: 'T',
      label: '27'
    }, {
      symbol: 'P',
      label: '28'
    }, {
      symbol: 'K',
      label: '29'
    }, {
      symbol: 'A',
      label: '30'
    }]
  }, {
    name: 'C',
    residues: [{
      symbol: 'G',
      label: '1'
    }, {
      symbol: 'I',
      label: '2'
    }, {
      symbol: 'V',
      label: '3'
    }, {
      symbol: 'E',
      label: '4'
    }, {
      symbol: 'Q',
      label: '5'
    }, {
      symbol: 'C',
      label: '6'
    }, {
      symbol: 'C',
      label: '7'
    }, {
      symbol: 'T',
      label: '8'
    }, {
      symbol: 'S',
      label: '9'
    }, {
      symbol: 'I',
      label: '10'
    }, {
      symbol: 'C',
      label: '11'
    }, {
      symbol: 'S',
      label: '12'
    }, {
      symbol: 'L',
      label: '13'
    }, {
      symbol: 'Y',
      label: '14'
    }, {
      symbol: 'Q',
      label: '15'
    }, {
      symbol: 'L',
      label: '16'
    }, {
      symbol: 'E',
      label: '17'
    }, {
      symbol: 'N',
      label: '18'
    }, {
      symbol: 'Y',
      label: '19'
    }, {
      symbol: 'C',
      label: '20'
    }, {
      symbol: 'N',
      label: '21'
    }]
  }, {
    name: 'D',
    residues: [{
      symbol: 'F',
      label: '1'
    }, {
      symbol: 'V',
      label: '2'
    }, {
      symbol: 'N',
      label: '3'
    }, {
      symbol: 'Q',
      label: '4'
    }, {
      symbol: 'H',
      label: '5'
    }, {
      symbol: 'L',
      label: '6'
    }, {
      symbol: 'C',
      label: '7'
    }, {
      symbol: 'G',
      label: '8'
    }, {
      symbol: 'S',
      label: '9'
    }, {
      symbol: 'H',
      label: '10'
    }, {
      symbol: 'L',
      label: '11'
    }, {
      symbol: 'V',
      label: '12'
    }, {
      symbol: 'E',
      label: '13'
    }, {
      symbol: 'A',
      label: '14'
    }, {
      symbol: 'L',
      label: '15'
    }, {
      symbol: 'Y',
      label: '16'
    }, {
      symbol: 'L',
      label: '17'
    }, {
      symbol: 'V',
      label: '18'
    }, {
      symbol: 'C',
      label: '19'
    }, {
      symbol: 'G',
      label: '20'
    }, {
      symbol: 'E',
      label: '21'
    }, {
      symbol: 'R',
      label: '22'
    }, {
      symbol: 'G',
      label: '23'
    }, {
      symbol: 'F',
      label: '24'
    }, {
      symbol: 'F',
      label: '25'
    }, {
      symbol: 'Y',
      label: '26'
    }, {
      symbol: 'T',
      label: '27'
    }, {
      symbol: 'P',
      label: '28'
    }, {
      symbol: 'K',
      label: '29'
    }, {
      symbol: 'A',
      label: '30'
    }]
  }]
};
